apiVersion: v1
kind: Service
metadata:
  labels:
    app: drupal
  name: drupal
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: drupal
